baseURL: "https://lucia-portfolio.netlify.app/"
languageCode: en-us
title: Portfolio website for Lucia Cai
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Masters in Analytics and Management @ LBS
    title: Lucia Cai
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Park Road
        title: London Business School
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: lcai.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 7749707827
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    #copyright: Company Name
    #enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    #social:
    #  - icon: fa-twitter
    #    label: Twitter
    #    url: https://www.twitter.com
    #  - icon: fa-facebook
    #    label: Facebook
    #    url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/_lucia_cai/
      - icon: fa-github
        label: GitHub
        url: https://github.com/luciacai
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/lucia-cai/
  image: ''
  name: Lucia Cai
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      #- name: Generic Blog
        #url: blogs/ipsum
      #- name: Elements
        #url: elements.html
    menu: Menu
#    subtitle: By HTML5 Up
    title: Lucia Cai
  tiles:
    enable: yes
    showcase: 
      - image: lbss.JPG
        subtitle: Who am I
        title: About me
        url: blogs/ipsum
        
      - image: coffee.jpeg
        subtitle: To know more about me
        title: Fun Facts about me
        url: blogs/tempus
        
      - image: wahu.jpeg
        subtitle: Analysis of Rent in San Francsisco
        title: Data Analytics Project 1
        url: blogs/hw1
        
      - image: cc.jpeg
        subtitle: Analysis of Climate change and temperature anomalies
        title: Data Analytics Project 2
        url: blogs/hw2
        
      - image: pic06.jpg
        subtitle: My resume
        title: My CV
        url: blogs/CV.pdf
        
      - image: ma.png
        subtitle: Business Model Analysis & LBO Model of M.P. Evans
        title: M&A case study
        url: blogs/LBS synergy.pdf
  two:
    buttonText: Get Started
    enable: yes
    subtitle: Thanks for your interest!
    title: Lucia Cai's portfolio
    url: blogs
