baseURL: "https://lucia-portfolio.netlify.app/"
languageCode: en-us
title: Portfolio website for Lucia Cai
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
#   subtitle: |-
#      A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
#      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Lucia Cai
  blog: {}
  contact:
    address:
      - city: London, NW8 7JS
        country: England
        street: 125 Park Road
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: lcai.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 7749707827
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    #copyright: Company Name
    #enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    #social:
    #  - icon: fa-twitter
    #    label: Twitter
    #    url: https://www.twitter.com
    #  - icon: fa-facebook
    #    label: Facebook
    #    url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/_lucia_cai/
      - icon: fa-github
        label: GitHub
        url: https://github.com/luciacai
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/lucia-cai/
  image: ''
  name: Lucia Cai
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      #- name: Generic Blog
        #url: blogs/ipsum
      #- name: Elements
        #url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbss.JPG
        subtitle: Who am I
        title: About me
        url: blogs/ipsum
      - image: pic02.jpg
        subtitle: To know more about me
        title: Fun facts
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Analysis of Rent in San Francsisco
        title: Data Analytics Project 1
        url: blogs/hw1
      - image: pic04.jpg
        subtitle: Analysis of Climate change and temperature anomalies
        title: Data Analytics Project 2
        url: blogs/hw2
      - image: pic05.jpg
        subtitle: My resume
        title: My CV
        url: blogs/CV.pdf
      - image: pic06.jpg
        subtitle: M.P Evans
        title: M&A Case Study
        url: blogs/LBS synergy.pdf
  two:
    buttonText: Get Started
    enable: yes
    subtitle: 
    title: Lucia Cai
    url: blogs
